liquids = {
    "water": {"color": "clear", "proof": 0, "hunger": 1, "thirst": 10},
    "beer": {
        "color": "amber",
        "proof": 12,
        "hunger": 1,
        "thirst": 8,
    },
    "red wine": {
        "color": "burgundy",
        "proof": 30,
        "hunger": 1,
        "thirst": 8,
    },
    "ale": {
        "color": "brown",
        "proof": 15,
        "hunger": 1,
        "thirst": 8,
    },
    "dark ale": {
        "color": "dark",
        "proof": 16,
        "hunger": 1,
        "thirst": 8,
    },
    "whisky": {
        "color": "golden",
        "proof": 120,
        "hunger": 1,
        "thirst": 5,
    },
    "lemonade": {
        "color": "pink",
        "proof": 0,
        "hunger": 1,
        "thirst": 9,
    },
    "firebreather": {
        "color": "boiling",
        "proof": 190,
        "hunger": 0,
        "thirst": 4,
    },
    "local specialty": {
        "color": "clear",
        "proof": 151,
        "hunger": 1,
        "thirst": 3,
    },
    "slime mold juice": {
        "color": "green",
        "proof": 0,
        "hunger": 2,
        "thirst": -8,
    },
    "milk": {
        "color": "white",
        "proof": 0,
        "hunger": 2,
        "thirst": 10,  # Original value was 9 but milk is the most refreshing
    },
    "tea": {
        "color": "tan",
        "proof": 0,
        "hunger": 1,
        "thirst": 8,
    },
    "coffee": {
        "color": "black",
        "proof": 0,
        "hunger": 1,
        "thirst": 8,
    },
    "blood": {
        "color": "red",
        "proof": 0,
        "hunger": 2,
        "thirst": -1,
    },
    "salt water": {
        "color": "clear",
        "proof": 0,
        "hunger": 1,
        "thirst": -2,
    },
    "coke": {
        "color": "brown",
        "proof": 0,
        "hunger": 2,
        "thirst": 9,
    },
    "root beer": {
        "color": "brown",
        "proof": 0,
        "hunger": 2,
        "thirst": 9,
    },
    "elvish wine": {
        "color": "green",
        "proof": 35,
        "hunger": 2,
        "thirst": 8,
    },
    "white wine": {
        "color": "golden",
        "proof": 28,
        "hunger": 1,
        "thirst": 8,
    },
    "champagne": {
        "color": "golden",
        "proof": 32,
        "hunger": 1,
        "thirst": 8,
    },
    "mead": {
        "color": "honey-colored",
        "proof": 34,
        "hunger": 2,
        "thirst": 8,
    },
    "rose wine": {
        "color": "pink",
        "proof": 26,
        "hunger": 1,
        "thirst": 8,
    },
    "benedictine wine": {
        "color": "burgundy",
        "proof": 40,
        "hunger": 1,
        "thirst": 8,
    },
    "vodka": {
        "color": "clear",
        "proof": 130,
        "hunger": 1,
        "thirst": 5,
    },
    "cranberry juice": {
        "color": "red",
        "proof": 0,
        "hunger": 1,
        "thirst": 9,
    },
    "orange juice": {
        "color": "orange",
        "proof": 0,
        "hunger": 2,
        "thirst": 9,
    },
    "absinthe": {
        "color": "green",
        "proof": 200,
        "hunger": 1,
        "thirst": 4,
    },
    "brandy": {
        "color": "golden",
        "proof": 80,
        "hunger": 1,
        "thirst": 5,
    },
    "aquavit": {
        "color": "clear",
        "proof": 140,
        "hunger": 1,
        "thirst": 5,
    },
    "schnapps": {
        "color": "clear",
        "proof": 90,
        "hunger": 1,
        "thirst": 5,
    },
    "icewine": {
        "color": "purple",
        "proof": 50,
        "hunger": 2,
        "thirst": 6,
    },
    "amontillado": {
        "color": "burgundy",
        "proof": 35,
        "hunger": 2,
        "thirst": 8,
    },
    "sherry": {
        "color": "red",
        "proof": 38,
        "hunger": 2,
        "thirst": 7,
    },
    "framboise": {
        "color": "red",
        "proof": 50,
        "hunger": 1,
        "thirst": 7,
    },
    "rum": {
        "color": "amber",
        "proof": 151,
        "hunger": 1,
        "thirst": 4,
    },
    "cordial": {
        "color": "clear",
        "proof": 100,
        "hunger": 1,
        "thirst": 5,
    },
}
